### ISSUE TITLE
[chore] update Go to 1.21, and update relevant pkgs

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/meshery-app-mesh#158]
### Desired Behaviour
Need to update `Go` to `1.21` in `go.mod` and in `Dockerfile`, and also `Makefile`

- Minor chore on updating `meshkit` and `meshery-adapter-library`

**Comment by captain-Akshay** [comment]
@saurabh100ni i would like to work on this!

**Comment by hemantmm** [comment]
Hi, @saurabh100ni can I start working on this issue?

**Comment by saurabh100ni** [comment]
@hemantmm let's assign this to @captain-Akshay as he came first,
There are other issues we would appreciate your contributions to.

**Comment by hemantmm** [comment]
Hi, @saurabh100ni can I take up this issue?

**Comment by saurabh100ni** [comment]
Hey @hemantmm @captain-Akshay is already working on this one. But that won't stop you from contributing.
Here's the link for more issues : [here](https://github.com/issues?q=is%3Aissue+is%3Aopen+user%3Ameshery+user%3Alayer5io+user%3Aservice-mesh-performance+user%3Aservice-mesh-patterns+label%3Ahacktoberfest+sort%3Acomments-asc)

**Comment by hemantmm** [comment]
ok
