### ISSUE TITLE
[CI] Patterns: Generate JSON Schema and Definitions for App Mesh components

### ISSUE THREAD

**Issue by Shreyas220** [meshery/meshery-app-mesh#55]
### Enhancement Description

To generate the workflow of getting the manifest from the App Mesh using the [kubeopenapi-jsonschema](https://github.com/layer5io/kubeopenapi-jsonschema) to read and generate json schemas from those manifests and then also generating workload definitions from those schemas.

A sample workflow is [here](https://github.com/DelusionalOptimist/meshery-istio/blob/gen-oam/.github/workflows/update-oam-defs.yml)

crds -> https://github.com/aws/aws-app-mesh-controller-for-k8s/tree/master/config/crd

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
-  Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Shreyas220** [comment]
hey @iamsdas following up, any progress ?

**Comment by iamsdas** [comment]
The existence of other folders in the [crds](https://github.com/aws/aws-app-mesh-controller-for-k8s/tree/master/config/crd) directory is causing some errors (it's trying to download the folder as a file) when trying to download them the [usual](https://github.com/meshery/meshery-osm/blob/ceb50f48d849488c3cfff32c3e2e5d60a74d5759/.github/workflows/update-oam-defs.yml#L50) way (usually there is only a single folder consisting of the `.yaml` files without any other directories). I was trying to figure out an ideal way to work around this when I got sidetracked and completely forgot about this issue 😓. I'll try to finish this soon.
