### ISSUE TITLE
Package static components with App Mesh adapter

### ISSUE THREAD

**Issue by utkarsh-pro** [meshery/meshery-app-mesh#61]
#### Current Behavior
Static Components are not packaged with docker containers

#### Expected Behavior
Static components must be packaged with docker containers

#### Environment

- **Host OS:** Linux
- **Platform:** Docker
- **Meshery Server Version:** any
- **Meshery Client Version:** any
- **Meshery Adapter Version:** any

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Revolyssup, for you?

**Comment by Revolyssup** [comment]
@utkarsh-pro  @leecalcote  I think this is because, the release was made 24 days ago and components were introduced 10 days ago. I am making a PR to fix the dynamic comp gen issue. Then a release will be needed

**Comment by leecalcote** [comment]
Good to close this one or is it still open?
