### ISSUE TITLE
Empty versions returned by getlatestreleasenames causing failing installations

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery-app-mesh#65]
#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Is https://github.com/meshery/meshery-app-mesh/pull/73 addressing this issue or will there be a separate fix here?

**Comment by Revolyssup** [comment]
> 

This issue is not related to #73

**Comment by leecalcote** [comment]
Is this issue a two-part item?

1. MeshKit to handle null values (I assume that it already does).
2. Identify a fallback routine in the event the latest release doesn't have a tag.

**Comment by Revolyssup** [comment]
Has been solved with new meshkit function
